(function(){
  "use strict";

  const PAGE_WIDTH=792;
  const PAGE_HEIGHT=612;
  const MARGIN=28;
  const CONTENT_WIDTH=PAGE_WIDTH-(MARGIN*2);
  const CONTENT_TOP=PAGE_HEIGHT-96;
  const CONTENT_BOTTOM=34;

  function clean(value){
    return String(value??"")
      .replace(/[\u2010-\u2015]/g,"-")
      .replace(/\u2022/g,"-")
      .replace(/[^\x20-\x7E]/g,"?")
      .replace(/\s+/g," ")
      .trim();
  }

  function wrapText(font,value,size,maxWidth){
    const text=clean(value);
    if(!text)return [];
    const lines=[];
    let current="";

    function pushLongWord(word){
      let chunk="";
      for(const character of word){
        const candidate=chunk+character;
        if(chunk&&font.widthOfTextAtSize(candidate,size)>maxWidth){
          lines.push(chunk);
          chunk=character;
        }else{
          chunk=candidate;
        }
      }
      current=chunk;
    }

    for(const word of text.split(" ")){
      if(!current){
        if(font.widthOfTextAtSize(word,size)>maxWidth)pushLongWord(word);
        else current=word;
        continue;
      }
      const candidate=current+" "+word;
      if(font.widthOfTextAtSize(candidate,size)<=maxWidth){
        current=candidate;
      }else{
        lines.push(current);
        current="";
        if(font.widthOfTextAtSize(word,size)>maxWidth)pushLongWord(word);
        else current=word;
      }
    }
    if(current)lines.push(current);
    return lines;
  }

  async function createCasePdf(data){
    if(!window.PDFLib)throw new Error("The PDF generator did not load.");
    const {PDFDocument,StandardFonts,rgb}=window.PDFLib;
    const pdf=await PDFDocument.create();
    pdf.setTitle("PDX Recovery Planner - Case Document");
    pdf.setAuthor("PDX Recovery Planner");
    pdf.setSubject("Validated recovery case document and supply list");
    pdf.setCreator("PDX Recovery Planner");

    const regular=await pdf.embedFont(StandardFonts.Helvetica);
    const bold=await pdf.embedFont(StandardFonts.HelveticaBold);
    const navy=rgb(7/255,31/255,62/255);
    const blue=rgb(11/255,99/255,206/255);
    const purple=rgb(111/255,66/255,193/255);
    const ink=rgb(28/255,28/255,30/255);
    const muted=rgb(90/255,90/255,96/255);
    const line=rgb(214/255,214/255,220/255);
    const pale=rgb(247/255,247/255,249/255);
    const white=rgb(1,1,1);
    const donor=clean(data.donor||"Case document");
    const generated=clean(data.generated||new Date().toLocaleString());
    let pageNumber=0;
    let state=null;

    function addPage(label){
      const page=pdf.addPage([PAGE_WIDTH,PAGE_HEIGHT]);
      pageNumber++;
      page.drawRectangle({x:0,y:PAGE_HEIGHT-48,width:PAGE_WIDTH,height:48,color:navy});
      page.drawText("PDX RECOVERY PLANNER",{x:MARGIN,y:PAGE_HEIGHT-29,size:15,font:bold,color:white});
      const header=clean(label).toUpperCase();
      page.drawText(header,{x:PAGE_WIDTH-MARGIN-bold.widthOfTextAtSize(header,9.5),y:PAGE_HEIGHT-28,size:9.5,font:bold,color:white});

      const donorLines=wrapText(bold,donor,9.5,455);
      donorLines.forEach((text,index)=>page.drawText(text,{x:MARGIN,y:PAGE_HEIGHT-64-(index*10.5),size:9.5,font:bold,color:navy}));
      const preparedLines=wrapText(regular,"Prepared "+generated,7.4,235);
      preparedLines.forEach((text,index)=>page.drawText(text,{x:PAGE_WIDTH-MARGIN-235,y:PAGE_HEIGHT-63-(index*9),size:7.4,font:regular,color:muted}));

      page.drawLine({start:{x:MARGIN,y:22},end:{x:PAGE_WIDTH-MARGIN,y:22},thickness:.6,color:line});
      page.drawText("Generated by PDX Recovery Planner",{x:MARGIN,y:10,size:6.5,font:regular,color:muted});
      const pageLabel="Page "+pageNumber;
      page.drawText(pageLabel,{x:PAGE_WIDTH-MARGIN-bold.widthOfTextAtSize(pageLabel,6.5),y:10,size:6.5,font:bold,color:muted});
      return {page,y:CONTENT_TOP,label};
    }

    function drawSectionHeader(title,continued){
      const label=clean(title)+(continued?" (continued)":"");
      const titleLines=wrapText(bold,label.toUpperCase(),9.2,CONTENT_WIDTH-14);
      const height=Math.max(18,(titleLines.length*10.5)+6);
      state.page.drawRectangle({x:MARGIN,y:state.y-height+4,width:CONTENT_WIDTH,height,color:pale});
      state.page.drawRectangle({x:MARGIN,y:state.y-height+4,width:3,height,color:purple});
      titleLines.forEach((text,index)=>state.page.drawText(text,{x:MARGIN+8,y:state.y-(index*10.5),size:9.2,font:bold,color:navy}));
      state.y-=height+3;
    }

    function continueCaseSection(title,minimumHeight){
      if(state.y-minimumHeight>=CONTENT_BOTTOM)return;
      state=addPage("Case details");
      drawSectionHeader(title,true);
    }

    function drawCaseRow(row,sectionTitle){
      const lines=wrapText(regular,row,8.25,CONTENT_WIDTH-8);
      for(const text of lines){
        continueCaseSection(sectionTitle,12);
        state.page.drawText(text,{x:MARGIN+4,y:state.y,size:8.25,font:regular,color:ink});
        state.y-=10.4;
      }
      continueCaseSection(sectionTitle,4);
      state.page.drawLine({start:{x:MARGIN,y:state.y+2},end:{x:MARGIN+CONTENT_WIDTH,y:state.y+2},thickness:.35,color:line});
      state.y-=3;
    }

    function drawGroupLabel(label,sectionTitle){
      const lines=wrapText(bold,clean(label).toUpperCase(),8,CONTENT_WIDTH-8);
      for(const text of lines){
        continueCaseSection(sectionTitle,11);
        state.page.drawText(text,{x:MARGIN+4,y:state.y,size:8,font:bold,color:blue});
        state.y-=9.8;
      }
    }

    function drawGroupItem(item,sectionTitle){
      const lines=wrapText(regular,"- "+item,7.8,CONTENT_WIDTH-18);
      for(const text of lines){
        continueCaseSection(sectionTitle,10.5);
        state.page.drawText(text,{x:MARGIN+12,y:state.y,size:7.8,font:regular,color:ink});
        state.y-=9.5;
      }
    }

    const sections=(data.sections||[]).map(section=>({
      title:clean(section.title),
      rows:(section.rows||[]).map(clean).filter(Boolean),
      groups:(section.groups||[]).map(group=>({
        label:clean(group.label),
        items:(group.items||[]).map(clean).filter(Boolean)
      })).filter(group=>group.label&&group.items.length)
    })).filter(section=>section.title);

    state=addPage("Case details");
    if(!sections.length){
      state.page.drawText("No case details were generated.",{x:MARGIN,y:state.y,size:9,font:regular,color:muted});
    }
    for(const section of sections){
      if(state.y-22<CONTENT_BOTTOM)state=addPage("Case details");
      drawSectionHeader(section.title,false);
      section.rows.forEach(row=>drawCaseRow(row,section.title));
      for(const group of section.groups){
        continueCaseSection(section.title,22);
        drawGroupLabel(group.label,section.title);
        group.items.forEach(item=>drawGroupItem(item,section.title));
        state.y-=3;
      }
      state.y-=7;
    }

    const supplies=(data.supplies||[]).map(item=>({
      name:clean(item.name),
      qty:clean(item.qty)
    })).filter(item=>item.name);

    function drawSupplyTableHeader(){
      state.page.drawRectangle({x:MARGIN,y:state.y-3,width:CONTENT_WIDTH,height:18,color:navy});
      state.page.drawText("SUPPLY",{x:MARGIN+7,y:state.y+1,size:8.5,font:bold,color:white});
      const qty="QUANTITY";
      state.page.drawText(qty,{x:MARGIN+CONTENT_WIDTH-7-bold.widthOfTextAtSize(qty,8.5),y:state.y+1,size:8.5,font:bold,color:white});
      state.y-=24;
    }

    function continueSupplies(minimumHeight){
      if(state.y-minimumHeight>=CONTENT_BOTTOM)return;
      state=addPage("Supplies to pull / log");
      drawSupplyTableHeader();
    }

    state=addPage("Supplies to pull / log");
    drawSupplyTableHeader();
    if(!supplies.length){
      state.page.drawText("No supplies were generated.",{x:MARGIN+4,y:state.y,size:9,font:regular,color:muted});
    }
    supplies.forEach((item,index)=>{
      const qtyWidth=82;
      const nameLines=wrapText(regular,item.name,8.2,CONTENT_WIDTH-qtyWidth-18);
      const qtyLines=wrapText(bold,item.qty,8.2,qtyWidth-8);
      const rowLines=Math.max(nameLines.length,qtyLines.length,1);
      const rowHeight=(rowLines*10)+6;
      continueSupplies(rowHeight);
      if(index%2===0)state.page.drawRectangle({x:MARGIN,y:state.y-rowHeight+4,width:CONTENT_WIDTH,height:rowHeight,color:pale});
      nameLines.forEach((text,lineIndex)=>state.page.drawText(text,{x:MARGIN+5,y:state.y-(lineIndex*10),size:8.2,font:regular,color:ink}));
      qtyLines.forEach((text,lineIndex)=>state.page.drawText(text,{
        x:MARGIN+CONTENT_WIDTH-5-bold.widthOfTextAtSize(text,8.2),
        y:state.y-(lineIndex*10),
        size:8.2,font:bold,color:navy
      }));
      state.y-=rowHeight;
      state.page.drawLine({start:{x:MARGIN,y:state.y+4},end:{x:MARGIN+CONTENT_WIDTH,y:state.y+4},thickness:.35,color:line});
    });

    return pdf.save();
  }

  window.PDXCasePdf={createCasePdf};
})();
