(function(){
  "use strict";
  let installed=false;

  function addStyles(){
    const style=document.createElement("style");style.id="desktopHomeStyles";style.textContent=`
.desktop-home-sidebar,.desktop-home-header,.desktop-summary,.desktop-top-actions{display:none}.desktop-home-grid,.desktop-home-cases,.desktop-home-rail{display:contents}
@media(min-width:1100px){
 :root{--desktop-side:188px}body{background:#eef3f8;color:#172233}header{height:68px;padding:0 22px;display:flex;align-items:center;background:#102f54}header .head{max-width:none;width:100%;margin:0;gap:18px}header .brand{font-size:18px;letter-spacing:.02em}header .ver{font-size:11px;opacity:.68;margin-top:3px}header .nav,#solvitaMenuButton,#plannerToolsButton{display:none!important}
 .desktop-top-actions{display:flex;align-items:center;gap:8px;margin-left:auto}.desktop-top-actions button{min-height:40px;border-radius:9px;padding:9px 13px;font-weight:760}.desktop-top-actions .desktop-schedule{color:#fff;background:transparent;border:1px solid #ffffff55}.desktop-top-actions .desktop-new{color:#fff;background:#16805b;border:1px solid #16805b}
 .desktop-home-sidebar{display:block;position:fixed;z-index:15;top:68px;left:0;bottom:0;width:var(--desktop-side);overflow:auto;background:#fff;border-right:1px solid #d9e1ea;padding:16px 11px}.desktop-side-label{padding:10px 10px 5px;color:#718096;font-size:10px;font-weight:850;letter-spacing:.09em;text-transform:uppercase}.desktop-side-button{width:100%;border:0;background:transparent;color:#34445a;border-radius:9px;padding:10px;display:flex;align-items:center;gap:9px;text-align:left;margin:2px 0;font-size:13px;font-weight:650}.desktop-side-button:hover{background:#f0f5fa}.desktop-side-button.active,.desktop-side-button[aria-expanded="true"]{background:#e7f0fa;color:#123f70;font-weight:800}.desktop-side-icon{width:20px;text-align:center;color:#55708c;font-size:15px}.desktop-side-chevron{margin-left:auto;color:#718096;font-size:10px}
 body>main{max-width:none;margin-left:var(--desktop-side);padding:20px 24px 30px}.desktop-home-header{display:flex;align-items:flex-start;gap:16px;margin-bottom:15px}.desktop-home-header h1{font-size:24px;line-height:1.15;margin:0;color:#172233}.desktop-home-header p{font-size:12px;color:#66768a;margin:5px 0 0}.desktop-date{margin-left:auto;font-size:12px;color:#66768a;padding-top:6px}#homeView>.tb-home-schedule{display:none!important}
 #homeView>.desktop-filter-card{padding:10px 12px;margin-bottom:12px;display:flex;align-items:center;gap:12px;box-shadow:none}#homeView>.desktop-filter-card h2{font-size:13px;margin:0;white-space:nowrap}#homeView>.desktop-filter-card>.small{display:none}#homeView>.desktop-filter-card .filters{margin:0;gap:5px}#homeView>.desktop-filter-card .chip{padding:7px 11px;font-size:12px;border-radius:8px}
 .desktop-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:14px}.desktop-summary-card{background:#fff;border:1px solid #dfe5ec;border-radius:11px;padding:11px 13px;display:flex;align-items:center;gap:11px;min-width:0}.desktop-summary-number{font-size:22px;font-weight:850;line-height:1}.desktop-summary-copy{min-width:0}.desktop-summary-name{display:block;font-size:12px;font-weight:800}.desktop-summary-detail{display:block;font-size:10px;color:#718096;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.desktop-summary-mark{width:5px;height:32px;border-radius:6px;background:#7b4ab8}.desktop-summary-card[data-status="planning"] .desktop-summary-mark{background:#2e8b57}.desktop-summary-card[data-status="in_progress"] .desktop-summary-mark{background:#0b63ce}.desktop-summary-card[data-status="complete"] .desktop-summary-mark{background:#777}
 .desktop-home-grid{display:grid;grid-template-columns:minmax(0,1fr) 285px;gap:15px;align-items:start}.desktop-home-cases,.desktop-home-rail{display:block;min-width:0}#board .section{margin-bottom:16px}#board .sectiontitle{font-size:13px;letter-spacing:.04em;color:#43556b;margin:0 0 7px;text-transform:uppercase}#board .grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}#board .donor{padding:12px;border-left-width:5px;border-radius:11px;box-shadow:0 2px 8px #0d223b0b}#board .name{font-size:16px}#board .demo{font-size:12px;color:#46586e;margin-top:2px}#board .pill{font-size:9px;margin:6px 0 3px;padding:3px 6px}#board .kv{font-size:11px;margin-top:5px}#board .note{font-size:11px;padding:7px}#board .actions{grid-template-columns:1fr auto;margin-top:8px}#board .actions button{font-size:11px;padding:8px 9px}#board .metrics{margin-top:7px}#board .ml{font-size:9px}#board .mv{font-size:15px}
 .desktop-home-rail #teamBoard{margin:0;padding:14px;border-radius:11px;box-shadow:0 2px 8px #0d223b0b}.desktop-home-rail #teamBoard h2{font-size:18px}.desktop-home-rail #teamBoard .tb-head{align-items:flex-start}.desktop-home-rail #teamBoard .tb-head>.tb-actions{display:grid;grid-template-columns:1fr 1fr;width:100%;margin-top:6px}.desktop-home-rail #teamBoard .tb-head>.tb-actions button:first-child{grid-column:1/-1}.desktop-home-rail #teamBoard .tb-toolbar{margin:10px 0}.desktop-home-rail #teamBoard select{width:100%}.desktop-home-rail #teamBoard .tb-item{grid-template-columns:1fr;gap:7px;padding:12px 0}.desktop-home-rail #teamBoard .tb-actions{gap:5px}.desktop-home-rail #teamBoard .tb-actions button{min-height:34px;padding:6px 8px;font-size:11px}.desktop-home-rail #teamBoard .tb-detail{font-size:12px;margin:5px 0}.desktop-home-rail #teamBoard .tb-muted{font-size:11px}#solvitaMenuPanel{display:none!important}
}@media(min-width:1280px){#board .grid{grid-template-columns:repeat(3,minmax(0,1fr))}.desktop-home-grid{grid-template-columns:minmax(0,1fr) 300px}}@media print{.desktop-home-sidebar,.desktop-home-header,.desktop-summary,.desktop-top-actions{display:none!important}body>main{margin-left:0}}
`;document.head.appendChild(style)
  }
  function clickMenu(label){const wanted=label.toUpperCase(),source=[...document.querySelectorAll("#solvitaMenuPanel button,#solvitaMenuPanel a,header .nav button")].find(el=>String(el.textContent||"").trim().toUpperCase().replace(/^OPEN /,"")===wanted);if(source){source.click();return true}return false}
  function updateActive(target){document.querySelectorAll(".desktop-side-button").forEach(button=>button.classList.toggle("active",button.dataset.target===target))}
  function navigate(target,label){if(target==="schedule")document.getElementById("tb-open-schedule")?.click();else if(typeof window.show==="function")window.show(target);else clickMenu(label);updateActive(target)}
  function makeButton(icon,label,target){const button=document.createElement("button");button.type="button";button.className="desktop-side-button";button.dataset.target=target;button.innerHTML=`<span class="desktop-side-icon" aria-hidden="true">${icon}</span><span>${label}</span>`;button.addEventListener("click",()=>navigate(target,label));return button}
  function makeToolsButton(){const button=document.createElement("button");button.id="desktopToolsButton";button.type="button";button.className="desktop-side-button";button.setAttribute("aria-haspopup","menu");button.setAttribute("aria-expanded","false");button.setAttribute("aria-controls","plannerToolsPanel");button.innerHTML='<span class="desktop-side-icon" aria-hidden="true">⚒</span><span>Tools</span><span class="desktop-side-chevron" aria-hidden="true">▾</span>';button.addEventListener("click",event=>{event.stopPropagation();if(window.PDXPlannerTools?.toggle)window.PDXPlannerTools.toggle();else document.getElementById("plannerToolsButton")?.click()});return button}
  function addSidebar(){const side=document.createElement("aside");side.className="desktop-home-sidebar";side.setAttribute("aria-label","Planner navigation");const group=(title,buttons)=>{const label=document.createElement("div");label.className="desktop-side-label";label.textContent=title;side.appendChild(label);buttons.forEach(x=>side.appendChild(makeButton(...x)))};group("Workspace",[["⌂","Home","home"],["◫","Schedule","schedule"],["✓","Staff","staff"]]);group("Directories",[["H","Hospitals","hospitals"],["F","Funeral homes","funerals"]]);group("Planner",[["◇","Graft criteria","criteria"]]);side.appendChild(makeToolsButton());side.appendChild(makeButton("▣","Archive","archive"));document.body.appendChild(side);updateActive("home")}
  function addTopActions(){const head=document.querySelector("header");if(!head||head.querySelector(".desktop-top-actions"))return;const actions=document.createElement("div");actions.className="desktop-top-actions";const schedule=document.createElement("button");schedule.type="button";schedule.className="desktop-schedule";schedule.textContent="Schedule";schedule.addEventListener("click",()=>navigate("schedule","Schedule"));const add=document.createElement("button");add.type="button";add.className="desktop-new";add.textContent="+ New donor";add.addEventListener("click",()=>{if(typeof window.newCase==="function")window.newCase();else clickMenu("NEW DONOR")});actions.append(schedule,add);head.appendChild(actions)}
  function addHomeHeader(home){const header=document.createElement("div");header.className="desktop-home-header";const copy=document.createElement("div");copy.innerHTML="<h1>Shift command center</h1><p>Active donors, timing, schedule, and team work in one view.</p>";const date=document.createElement("div");date.className="desktop-date";date.textContent=new Intl.DateTimeFormat("en-US",{weekday:"long",month:"short",day:"numeric"}).format(new Date());header.append(copy,date);home.prepend(header)}
  function addSummary(home){const summary=document.createElement("section");summary.className="desktop-summary";summary.setAttribute("aria-label","Donor status summary");for(const [status,name,detail] of [["pending","Pending","Needs review"],["planning","Planning","Ordered by start time"],["in_progress","In OR","Elapsed time shown below"],["complete","Completed","Ready for handoff"]]){const card=document.createElement("div");card.className="desktop-summary-card";card.dataset.status=status;card.innerHTML=`<span class="desktop-summary-mark"></span><span class="desktop-summary-number" data-summary-count="${status}">0</span><span class="desktop-summary-copy"><span class="desktop-summary-name">${name}</span><span class="desktop-summary-detail">${detail}</span></span>`;summary.appendChild(card)}const filter=home.querySelector(":scope>.card");filter?.classList.add("desktop-filter-card");filter?.after(summary)}
  function arrangeColumns(home){const board=document.getElementById("board");if(!board)return;const grid=document.createElement("div"),cases=document.createElement("section"),rail=document.createElement("aside");grid.className="desktop-home-grid";cases.className="desktop-home-cases";rail.className="desktop-home-rail";rail.setAttribute("aria-label","Team board");board.before(grid);grid.append(cases,rail);cases.appendChild(board);const move=()=>{const team=document.getElementById("teamBoard");if(team&&!rail.contains(team))rail.appendChild(team)};move();new MutationObserver(move).observe(home,{childList:true,subtree:true})}
  function updateCounts(){const counts={pending:0,planning:0,in_progress:0,complete:0};document.querySelectorAll("#board .section").forEach(section=>{const title=String(section.querySelector(".sectiontitle")?.textContent||"").toUpperCase(),key=title.startsWith("PENDING")?"pending":title.startsWith("PLANNING")?"planning":title.startsWith("IN PROGRESS")?"in_progress":title.startsWith("COMPLETED")?"complete":null;if(key)counts[key]=section.querySelectorAll(".donor").length});for(const [key,count] of Object.entries(counts)){const node=document.querySelector(`[data-summary-count="${key}"]`);if(node)node.textContent=String(count)}}
  function watchViews(){const main=document.querySelector("body>main");if(!main)return;const sync=()=>{const pairs=[["homeView","home"],["plannerView","home"],["hospitalsView","hospitals"],["funeralsView","funerals"],["staffView","staff"],["criteriaView","criteria"],["archiveView","archive"]],visible=pairs.find(([id])=>{const el=document.getElementById(id);return el&&!el.classList.contains("hidden")});if(visible)updateActive(visible[1])};new MutationObserver(sync).observe(main,{attributes:true,subtree:true,attributeFilter:["class"]});sync()}
  function install(){if(installed)return;const home=document.getElementById("homeView");if(!home)return;installed=true;addStyles();addSidebar();addTopActions();addHomeHeader(home);addSummary(home);arrangeColumns(home);watchViews();const board=document.getElementById("board");if(board){new MutationObserver(updateCounts).observe(board,{childList:true,subtree:true});updateCounts()}}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install);else install()
})();
